GOOGLE_CALENDAR_DATETIME_FORMAT_WITHOUT_TIMEZONE = '%Y-%m-%dT%H:%M:%SZ'
GOOGLE_CALENDAR_DATETIME_FORMAT_WITH_TIMEZONE = '%Y-%m-%dT%H:%M:%S%z'
GOOGLE_CALENDAR_DATETIME_TOKEN_JSON_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
