name: Manual synchronize

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Poetry install
        run: pip install poetry

      - name: Run a script
        run: |
            poetry run snookxporter --token '${{ secrets.CALENDAR_TOKEN }}'
