name: Run tests

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Poetry install
        run: pip install poetry

      - name: Run tests
        run: make tests
